- hosts: terraform-ansible
  tasks:
    - name: Installing python 3 and virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update-cache: true
      become: yes
    - name: Installing python dependicies with pip
      ansible.builtin.pip:
        virtualenv: /home/ubuntu/python-example/venv
        name:
          - django
          - djangorestframework
