- hosts: terraform-ansible
  tasks:
    - name: Installing python 3 and virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update-cache: true
      become: yes
    - name: Installing python dependicies with pip
      ansible.builtin.pip:
        virtualenv: /home/ubuntu/python-example/venv
        name:
          - django
          - djangorestframework
    - name: Init project
      ansible.builtin.shell: ". /home/ubuntu/python-example/venv/bin/activate; django-admin startproject setup /home/ubuntu/python-example"
    - name: Change hosts 
      lineinfile:
        path: /home/ubuntu/python-example/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS= ["*"]'
        backrefs: yes